# Generated by Django 2.0.6 on 2018-09-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='is_repost',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='re_post',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='re_poster',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profil',
            field=models.ImageField(default='profiles/default/profil.png', upload_to=''),
        ),
    ]
