# Generated by Django 2.0.6 on 2018-10-02 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dreamteam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='_from',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='_to',
        ),
        migrations.AddField(
            model_name='chat',
            name='dreamteam',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dreamteam.Dreamteam'),
        ),
    ]
