# Generated by Django 2.0.6 on 2018-10-02 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dreamteam', '0002_auto_20181002_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='dreamteam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dreamteam.Dreamteam'),
        ),
    ]
