# Generated by Django 2.0.6 on 2018-10-02 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dreamteam', '0003_auto_20181002_1120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-sendtime']},
        ),
        migrations.RemoveField(
            model_name='chat',
            name='_from',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='_to',
        ),
        migrations.AddField(
            model_name='chat',
            name='comefrom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comefrom', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cometo', to=settings.AUTH_USER_MODEL),
        ),
    ]
