# Generated by Django 2.0.6 on 2018-10-02 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dreamteam', '0004_auto_20181002_1142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['sendtime']},
        ),
    ]
