# Generated by Django 2.0.6 on 2018-10-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamteam', '0005_auto_20181002_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='unread',
            field=models.BooleanField(default=False),
        ),
    ]
